ContestantApp/ContestantApp/Controllers/ContestantInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Contestant.Entities.Models;
using ContestantApp.Models;
using System.Globalization;
using Newtonsoft.Json;
using PagedList;
using Contestant.Repository.IRepos;

namespace ContestantApp.Controllers
{
    public class ContestantInfoesController : Controller
    {
        private IContestantInfoRepo _cinfo;
        private IDistriceRepo _dist;

        public ContestantInfoesController(IContestantInfoRepo cr, IDistriceRepo _dist)
        {
            this._cinfo = cr;
            this._dist = _dist;
        }

        // GET: ContestantInfoes
        public ActionResult Index(int? page)
        {
            var contestantInfoes = _cinfo.GetAll().ToList();

            //paging
            var pageNumber = page ?? 1;
            var itemPerPage = contestantInfoes.ToPagedList(pageNumber,5);
            return View(itemPerPage);
        }
        

        // GET: ContestantInfoes/Create
        public ActionResult Create()
        {
            ContestantCreateViewModel crm = new ContestantCreateViewModel();
            crm.Gender = false;
            ViewBag.DistrictId = new SelectList(_dist.GetAll().ToList(), "Id", "Name");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContestantCreateViewModel contestantInfo)
        {
            if (ModelState.IsValid)
            {
                var file = contestantInfo.Image;
                string _imageUID = DateTime.Now.ToString("yyyyMMddHHmmssfff");
                string fileLocation="";
                if (file != null && file.ContentLength > 0)
                {
                    var filename = file.FileName;
                    var _newfilename = _imageUID;
                    fileLocation = string.Format("{0}/{1}{2}", "/images", _newfilename, System.IO.Path.GetExtension(filename));
                    string saveat = string.Format("{0}/{1}{2}", Server.MapPath("~/images"), _newfilename, System.IO.Path.GetExtension(filename));
                    file.SaveAs(saveat);
                }

                var dob = DateTime.ParseExact(contestantInfo.Dob, "MM/dd/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                var contestant = new ContestantInfo()
                {
                    FirstName=contestantInfo.FirstName,
                    LastName=contestantInfo.LastName,
                    DateOfBirth =dob,
                    IsActive=contestantInfo.IsActive,
                    DistrictId=contestantInfo.DistrictId,
                    PhotoUrl=fileLocation,
                    Address=contestantInfo.Address
                };

                if(contestantInfo.Gender==false||contestantInfo.Gender==null)
                {
                    contestant.Gender = "female";
                }
                else
                {
                    contestant.Gender = "male";
                }

                _cinfo.Create(contestant);
                _cinfo.Save();
                return RedirectToAction("Index");
            }

            ViewBag.DistrictId = new SelectList(_dist.GetAll().ToList(), "Id", "Name", contestantInfo.DistrictId);
            return View(contestantInfo);
            
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContestantInfo contestantInfo = _cinfo.FindByID(id);
            /*var date = Convert.ToString(contestantInfo.DateOfBirth);
            var dob = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);*/
            var contestantvm = new ContestantEditViewModel()
            {
                ContestantID = contestantInfo.Id,
                FirstName = contestantInfo.FirstName,
                LastName = contestantInfo.LastName,
                Dob = contestantInfo.DateOfBirth.ToString(),
                IsActive = contestantInfo.IsActive,
                DistrictId = Convert.ToInt32(contestantInfo.DistrictId),
                ImageUrl = contestantInfo.PhotoUrl,
                Address = contestantInfo.Address
            };

            if (contestantInfo.Gender == "female")
            {
                contestantvm.Gender = false;
            }
            else
            {
                contestantvm.Gender = true;
            }
            if (contestantvm == null)
            {
                return HttpNotFound();
            }
            ViewBag.DistrictId = new SelectList(_dist.GetAll().ToList(), "Id", "Name", contestantInfo.DistrictId);
            return View(contestantvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContestantEditViewModel contestantvm)
        {
            //to Edit Image or photo
            //create separate page
            // like edit photo
            // but not now
            if (ModelState.IsValid)
            {
                var contestant = _cinfo.FindByID(contestantvm.ContestantID);
                bool chk = this.chkIfDateParsabel(contestantvm.Dob);
                DateTime? dob=null;
               if(chk==true)
               {
                   dob = DateTime.ParseExact(contestantvm.Dob, "MM/dd/yyyy", System.Globalization.CultureInfo.InvariantCulture);
               }
               else
               {
                   dob=Convert.ToDateTime(contestantvm.Dob);
               }
               
                contestant.FirstName = contestantvm.FirstName;
                contestant.LastName = contestantvm.LastName;
                contestant.DateOfBirth = dob;
                contestant.IsActive = contestantvm.IsActive;
                contestant.DistrictId = contestantvm.DistrictId;
                contestant.PhotoUrl = contestantvm.ImageUrl;
                contestant.Address = contestantvm.Address;

                if (contestantvm.Gender == false)
                {
                    contestant.Gender = "female";
                }
                else
                {
                    contestant.Gender = "male";
                }


                _cinfo.Edit(contestant);
                _cinfo.Save();
                return RedirectToAction("Index");
            }
            ViewBag.DistrictId = new SelectList(_dist.GetAll().ToList(), "Id", "Name", contestantvm.DistrictId);
            return View(contestantvm);
        }

        private bool chkIfDateParsabel(string d)
        {
            bool _ok = false;
            try
            {
                var dob = DateTime.ParseExact(d, "MM/dd/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                _ok = true;
                return _ok;
            }
            catch(Exception ex)
            {
                return _ok;
            }
        }

        // GET: ContestantInfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContestantInfo contestantInfo = _cinfo.FindByID(id);
            if (contestantInfo == null)
            {
                return HttpNotFound();
            }
            return View(contestantInfo);
        }

        // POST: ContestantInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ContestantInfo contestantInfo = _cinfo.FindByID(id);
            _cinfo.Delete(contestantInfo);
            _cinfo.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _cinfo.Dispose();
                _dist.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContestantApp/ContestantApp/Controllers/ContestantRatingController.cs
using Contestant.Entities.Models;
using Contestant.Repository.IRepos;
using ContestantApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ContestantApp.Controllers
{
    public class ContestantRatingController : Controller
    {
        private IContestantRatingRepo _crate;
        private IContestantInfoRepo _cinfo;

        public ContestantRatingController(IContestantRatingRepo _crate, IContestantInfoRepo _cinfo)
        {
            this._crate = _crate;
            this._cinfo = _cinfo;
        }

        // GET: ContestantRating

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetActiveContestantRating(DateTime? _from,DateTime? to)
        {
            try
            {
                var _crVMList = this.GetContestRatingVMList(_from, to);
                if (_crVMList.Count() > 0)
                {
                    var jdata = JsonConvert.SerializeObject(_crVMList);
                    return Json(jdata, JsonRequestBehavior.AllowGet);
                }
                return Json( JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        private List<ContestantRatingViewModel> GetContestRatingVMList(DateTime? _from, DateTime? to)
        {
            try
            {
                List<ContestantRatingViewModel> crVMList = new List<ContestantRatingViewModel>();
                var activeContestant = _cinfo.GetActiveContestant();
                var contestantRated = _crate.GetAll().ToList();
                if (contestantRated.Count() > 0)
                {
                    if (activeContestant.Count() > 0)
                    {
                        DateTime? min = null;
                        DateTime? max = null;
                        if (_from == null || to == null)
                        {
                            max = contestantRated.Max(x => x.RatedDate);
                            min = contestantRated.Min(x => x.RatedDate);
                        }
                        else
                        {
                            if (_from > to)
                            {
                                max = _from;
                                min = to;
                            }
                            else
                            {
                                max = to;
                                min = _from;
                            }
                        }
                        var _countBetweenDate = (from x in contestantRated where x.RatedDate >= min where x.RatedDate <= max select x).ToList();

                        var _dividBy = _countBetweenDate.Count();
                        if (_dividBy == 0)
                        {
                            _dividBy = 1;
                        }

                        foreach (var item in activeContestant)
                        {
                            var contestantId = item.Id;
                            var ratedContestant = _crate.FindByContestantID(contestantId);
                            var sumRate = ratedContestant.Sum(x => x.Rating);

                            var a = Convert.ToDecimal(sumRate) / _dividBy;
                            var avgRating =Math.Round(a, 2) ;

                            ContestantRatingViewModel crvM = new ContestantRatingViewModel()
                            {
                                ContestantId = item.Id,
                                AverageRating = avgRating,
                                FirstName = item.FirstName,
                                LastName = item.LastName,
                                District = item.District.Name,
                                DOB = item.DateOfBirth.ToString()
                            };
                            crVMList.Add(crvM);
                        }

                        return crVMList;
                    }
                    return crVMList;
                }
                else
                {
                    foreach (var item in activeContestant)
                    {
                        var contestantId = item.Id;
                        var avgRating = 0;

                        ContestantRatingViewModel crvM = new ContestantRatingViewModel()
                        {
                            ContestantId = item.Id,
                            AverageRating = avgRating,
                            FirstName = item.FirstName,
                            LastName = item.LastName,
                            District = item.District.Name,
                            DOB = item.DateOfBirth.ToString()
                        };
                        crVMList.Add(crvM);
                    }
                    return crVMList;
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult RateContestant(ContestantRating cr)
        {
            if(cr!=null)
            {
                cr.RatedDate = DateTime.Now;
                _crate.Create(cr);
                _crate.Save();

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _crate.Dispose();
                _cinfo.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

ContestantApp/ContestantApp/Controllers/GalleryController.cs
using Contestant.Entities.Models;
using Contestant.Repository.IRepos;
using ContestantApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContestantApp.Controllers
{
    public class GalleryController : Controller
    {

        private IContestantInfoRepo _cinfo;
        
        // GET: Gallery

        public GalleryController(IContestantInfoRepo _cinfo)
        {
            this._cinfo=_cinfo;
        }
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetGallareyData()
        {
            List<GallaeryViewMode> gvmL = new List<GallaeryViewMode>();
            var contestant = _cinfo.GetAll().ToList();
            var active = (from x in contestant where x.IsActive == true select x).ToList();
            foreach(var item in active)
            {
                GallaeryViewMode gvm = new GallaeryViewMode();
                gvm.ContestantID = item.Id;
                gvm.PhotoUrl = item.PhotoUrl;
                gvmL.Add(gvm);
            }
            
            
            var jdata = JsonConvert.SerializeObject(gvmL);
            return Json(jdata, JsonRequestBehavior.AllowGet);
        }
    }
}

ContestantApp/ContestantApp/Controllers/MapController.cs
using Contestant.Repository.IRepos;
using ContestantApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContestantApp.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        private IContestantInfoRepo _cinfo;
        //private IDistriceRepo _dist;

        public MapController(IContestantInfoRepo _cinfo)
        {
            this._cinfo = _cinfo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetContestantFromDistrict(int _dID)
        {
            var allContestant = _cinfo.GetAll().ToList();
            var _districtContestant = (from x in allContestant where x.DistrictId == _dID select x).ToList();

            List<MapViewModel> mvmL = new List<MapViewModel>();
            foreach(var item in _districtContestant)
            {
                MapViewModel mvm = new MapViewModel()
                {
                    FirstName=item.FirstName,
                    LastName=item.LastName,
                    Dob=item.DateOfBirth.ToString(),
                    Gender=item.Gender
                };

                mvmL.Add(mvm);
            }
            var jdata = JsonConvert.SerializeObject(mvmL);
            return Json(jdata,JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _cinfo.Dispose();
                // _dist.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContestantApp/ContestantApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en" class="no-js">

<!-- start: HEAD -->
<head>
    <title>Contestant</title>
    <!-- start: META -->
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    @Styles.Render("~/Content/ClipOneCss/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="shortcut icon" href="~/Content/favicon.ico" />
    <style>
        .icon {
            max-width: 40%;
            max-height: 40%;
        }

        ul.main-navigation-menu > li.active > a {
            background: #287DA5 !important;
            border-top: none !important;
            color: #fff;
        }

        #header {
            background: rgb(219, 219, 219);
        }
    </style>

</head>
<!-- end: HEAD -->
<!-- start: BODY -->
<body>
    <!-- start: HEADER -->
    <div class="navbar navbar-inverse navbar-fixed-top" id="header">
        <!-- start: TOP NAVIGATION CONTAINER -->
        <div class="container">
            <div class="navbar-header">
                <!-- start: RESPONSIVE MENU TOGGLER -->
                <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                    <span class="clip-list-2"></span>
                </button>
                <!-- end: RESPONSIVE MENU TOGGLER -->
                <!-- start: LOGO -->
                <a class="navbar-brand" href="">
                    <img src="/Content/images/logo1.png" class="icon" />
                </a>
                <!-- end: LOGO -->
            </div>
            <div class="navbar-tools">
                <ul class="nav navbar-right"></ul>
            </div>
        </div>
    </div>
    <!-- end: HEADER -->
    <!-- start: MAIN CONTAINER -->
    <div class="main-container">
        <div class="navbar-content">
            <!-- start: SIDEBAR -->
            <div class="main-navigation navbar-collapse collapse">

                <!-- start: MAIN MENU TOGGLER BUTTON -->
                <div class="navigation-toggler">
                    <i class="clip-chevron-left"></i>
                    <i class="clip-chevron-right"></i>
                </div>
                <!-- end: MAIN MENU TOGGLER BUTTON -->
                <!-- start: MAIN NAVIGATION MENU -->
                <ul class="main-navigation-menu">

                    <li>
                        <a href="@Url.Action("Index","ContestantInfoes")">
                            <i class="clip-user-6"></i>
                            <span class="title"> Contestant </span><span class="selected"></span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "ContestantRating")">
                            <i class="clip-star-4"></i>
                            <span class="title">Contestant Rating</span><i class="selected"></i>
                            <span class="selected"></span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Gallery")">
                            <i class="clip-images"></i>
                            <span class="title"> Photo Gallery </span><i class="selected"></i>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Map")">
                            <i class="clip-locked"></i>
                            <span class="title"> Map </span><i class="selected"></i>
                            <span class="selected"></span>
                        </a>
                    </li>

                </ul>
                <!-- end: MAIN NAVIGATION MENU -->
            </div>
            <!-- end: SIDEBAR -->
        </div>
        <!-- start: PAGE -->
        <div class="main-content">

            <div class="container">
                <!-- start: PAGE HEADER -->
                <div class="row">
                    <div class="col-sm-12">

                        <!-- start: PAGE TITLE & BREADCRUMB -->
                        <div id="pagetitle">
                            @if (IsSectionDefined("PageTitle"))
                            {
                                @RenderSection("PageTitle", required: false)
                            }
                        </div>

                        <div class="page-header">
                            <h1> <small></small></h1>
                        </div>
                        <!-- end: PAGE TITLE & BREADCRUMB -->
                    </div>
                </div>
                <!-- end: PAGE HEADER -->
                <!-- start: PAGE CONTENT -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- start: INBOX PANEL -->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <i class="icon-external-link-sign"></i>
                            </div>
                            <div class="panel-body">
                                @RenderBody()

                            </div>
                        </div>
                    </div>
                    <!-- end: INBOX PANEL -->
                </div>
            </div>
            <!-- end: PAGE CONTENT-->
        </div>
    </div>
    <!-- end: PAGE -->
    <!-- end: MAIN CONTAINER -->
    <!-- start: FOOTER -->
    <div class="footer clearfix">
        <div class="footer-inner">
            &#64;@DateTime.Now.ToString("yyyy/MM/dd") &copy;Rabin Prajapati.
        </div>
        <div class="footer-items">
            <span class="go-top"><i class="clip-chevron-up"></i></span>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/ClipOne")
        @RenderSection("scripts", required: false)
        <script>
            jQuery(document).ready(function () {
                Main.init();
            });
        </script>
    </div>

</body>
<!-- end: BODY -->
</html>